### ISSUE TITLE
[ Feature Request ] web interface

### ISSUE THREAD

**Issue by joshbmarshall** [duzda/deezer-enhanced#28]
Since deezer is taking forever to get remote control of devices working, it would be fantastic if there was a simple web interface in deezer-enhanced (probably on a configurable / other tcp port) where we can skip next / back, play-pause and hit favorite or not. Pretty much the items in the tray icon menu.

That would be fantastic!

**Comment by duzda** [comment]
Hello!

I'm not really sure if I understand properly, since I've never really used remote control, I believe Spotify somewhat implements this feature, I remember being able to next/back my music with my phone while the music is being played on the computer. Which sounds great, may not be really feasible, since this would require custom phone app or be available only in the same network or require support from the backend, which is probably missing.

Opening a new port sounds doable, but once again, this would be only usable if the remote device can communicate with the port and probably only in the same network.

Please give a further insight and let me know, whether this link,
https://en.deezercommunity.com/product-updates/try-our-remote-control-and-let-us-know-how-it-works-70079/index3.html#
kinda contains what you propose.

**Comment by joshbmarshall** [comment]
Sure thing, I know that with Spotify it works back to their servers, so you can remote control what's playing in the car from home etc. It doesn't make sense to need that level of remote control as it just messes with whoever's driving!

Deezer's implementation of remote control has been years in the making and only for iOS.

In my use case I have a computer running on the hifi and have another computer I'm working on in the room and am a bit lazy don't want to get up and walk over to skip a song.

At the moment I'm ssh'ing across to the linux computer running deezer-enhanced and using playerctl to skip to the next song.

With nodejs I know you can create a web server using the express module. I was thinking there could be a REST interface maybe using a Vue app or similar that could load up in a web browser across the local network that interacts with deezer-enhanced by giving back / next / playpause / favorite / unfavorite etc. It might be able to give current song playing name but not necessarily search and queue songs etc. Just a simple remote control for now.

I've done a little with express app on node, and I can run deezer-enhanced from yarn so I might be able to create something and send a pull request.

**Comment by duzda** [comment]
Cool, glad the limitations are clear!

I really like this idea, although I've never created an nodejs server app. imo it doesn't have to be anything super fancy, therefore I don't think Vue etc. is neccessary, pure javascript might suffice. Also, I'd like to keep the number of dependencies as low as possible, as the app is already slow in it's current state.

Feel free to open a pull request. if not, I might implement this myself sometime in the future.

**Comment by joshbmarshall** [comment]
Thanks, I've had a go and created a pull request #29 - It's not perfect, and could still have favorite toggle and even progress through the track. I may add these later.

**Comment by duzda** [comment]
Very clean! Thanks!
