### ISSUE TITLE
Audio sample rate

### ISSUE THREAD

**Issue by asardaes** [duzda/deezer-enhanced#45]
Hello, I have been using deezer-enhanced on Arch Linux for a while without issues. I currently use [PipeWire with multiple allowed sample rates](https://wiki.archlinux.org/title/PipeWire#Changing_the_allowed_sample_rate(s)), and my DAC always shows 48 kHz when using deezer-enhanced. Mostly out of curiosity, I wanted to know if this is under your control somehow? I thought maybe it was an electron limitation, but I think Spotify also uses electron and it does make my DAC show 44.1 kHz.

Side note: a lot of sites online say Deezer streams FLAC at 44.1 kHz, but I can't actually find confirmation in Deezer's official site, so who knows, they may have switched to 48 kHz server-side anyway.

**Comment by duzda** [comment]
Hello, 
glad you're enjoying the app! I haven't changed anything regarding audio. It might be either very easy to change audio settings or complicated due to encryption. [Deezer](https://support.deezer.com/hc/en-gb/articles/115004588345-High-Fidelity-HiFi-) states they use 44.1kHz and it seems like electron doesn't have any hard coded limit for sampling rate, so it can probably use any rate. If in doubt, you can check on the website. I will be honest with you, I do not really understand all the things such as sampling rate, I'm using a rather simple setup, just know the better the sampling rate, the better the output :)

**Comment by asardaes** [comment]
Thanks for the info. Consensus for sampling rate is all over the place, but I think more isn't always better, and resampling is probably fine, I just avoid it if it's easily doable.

I also tried the official deezer app and that seems to have the same behavior, so who knows. Maybe I'll ask them directly in one of their forums.
